spring:
  application:
    name: spring-boot-integration-zk
  zk:
    connection-timeout: 5000
    zkServers: 192.168.3.101:2181,192.168.3.102:2181,192.168.3.103:2181
    sessionTimeout: 10000
    maxRetries: 3
    maxSleepTime: 2000
    namespace: test
